FROM node:20.11-alpine as build
WORKDIR /usr/local/app
COPY ./ /usr/local/app/
RUN npm install --no-audit
RUN npm run build

FROM nginx:1.25.3
COPY --from=build /usr/local/app/dist/frontend /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf